### ISSUE TITLE
PDU Timeout

### ISSUE THREAD

**Issue by hewittwill** [PantelisGeorgiadis/dcmjs-dimse#6] opened 2021-11-09 22:15 UTC
60s after a successful C-STORE, the logger logs `Max PDU Timeout Exceeded` - is this expected behaviour?

**Comment by PantelisGeorgiadis** [comment] 2021-11-12 07:51
Hello @hewittwill! Thank you for your comment! It is an expected behavior BUT only if there is pending PDU(s) to be sent/received and the default timeout has passed. I've tested with a third-party client and can't reproduce it. Is your client trying to send more information after the C-STORE operation? In any case, you can adjust the timeout values with `opts.connectTimeout`, `opts.associationTimeout` and `opts.pduTimeout` for both `Client` and `Server`.

**Comment by hewittwill** [comment] 2021-11-15 20:55
This was observed using Horos to send, which is a free DICOM viewer. Uncertain if its doing something wrong or not, we'll test with a couple more clients. 

Related question - is there somewhere to configure the Max PDU Size, like in Pynetdicom (similar library to yours, but in Python) to increase transfer speed?

**Comment by PantelisGeorgiadis** [comment] 2021-11-16 13:38
Hello @hewittwill! I know Horos! I used it during the development of this library. I just verified that I can't see the same thing using Horos v4.0.0 RC3. Could you please go deeper and debug what's the type of the PDU that times-out?

Regarding setting the maximum PDU Length, yes, of course there is a way! In the `associationRequested` handler, you can set the desired max PDU length by calling `this.association.setMaxPduLength(XXXXX);` before accepting (or rejecting) the association.

**Comment by PantelisGeorgiadis** [comment] 2021-12-04 13:28
Hello @hewittwill! Closing the issue now. If you feel that we can do more on that, please reopen or create a new issue.

**Closed by PantelisGeorgiadis** 2021-12-04 13:28 UTC
Labels: question
